import katex from "katex"
import { katexCss } from "../generated/katexCss"

export interface MathSnippet {
  id: string
  tex: string
  displayMode: boolean
}

let idCounter = 0

function nextId(): string {
  return `__MATH_${idCounter++}__`
}

const BLOCK_PLACEHOLDER = (id: string) =>
  `<div class="math-block-placeholder" data-math="${id}"></div>`
const INLINE_PLACEHOLDER = (id: string) =>
  `<span class="math-inline-placeholder" data-math="${id}"></span>`

/**
 * Extract LaTeX math expressions from Markdown and replace them with
 * placeholders so that the Markdown parser does not corrupt them.
 */
export function extractMath(markdown: string): {
  prepared: string
  snippets: MathSnippet[]
} {
  idCounter = 0
  const snippets: MathSnippet[] = []

  let prepared = markdown.replace(/\$\$([\s\S]*?)\$\$/g, (_, rawTex: string) => {
    const id = nextId()
    snippets.push({ id, tex: rawTex.trim(), displayMode: true })
    return BLOCK_PLACEHOLDER(id)
  })

  prepared = prepared.replace(
    /(?<!\$)\$([^$\n]+?)\$(?!\$)/g,
    (_, rawTex: string) => {
      const id = nextId()
      snippets.push({ id, tex: rawTex.trim(), displayMode: false })
      return INLINE_PLACEHOLDER(id)
    }
  )

  return { prepared, snippets }
}

interface CssRule {
  selector: string
  styles: Record<string, string>
}

/**
 * Lightweight CSS parser that works in both the browser and jsdom.
 * Handles the subset of CSS generated by KaTeX.
 */
function parseCss(cssText: string): CssRule[] {
  const rules: CssRule[] = []
  // Remove comments.
  const cleaned = cssText.replace(/\/\*[\s\S]*?\*\//g, "")
  // Split into rule blocks.
  const blocks = cleaned.split("}")

  for (const block of blocks) {
    const openIdx = block.indexOf("{")
    if (openIdx === -1) continue

    const selectorPart = block.slice(0, openIdx).trim()
    const declarationPart = block.slice(openIdx + 1).trim()
    if (!selectorPart || !declarationPart) continue

    const selectors = selectorPart.split(",").map((s) => s.trim())
    const declarations: Record<string, string> = {}

    for (const decl of declarationPart.split(";")) {
      const colonIdx = decl.indexOf(":")
      if (colonIdx === -1) continue
      const prop = decl.slice(0, colonIdx).trim()
      const value = decl.slice(colonIdx + 1).trim()
      if (prop && value) {
        declarations[prop] = value
      }
    }

    for (const selector of selectors) {
      if (!selector) continue
      rules.push({ selector, styles: { ...declarations } })
    }
  }

  return rules
}

/**
 * Inline KaTeX CSS styles into the rendered HTML.
 *
 * WeChat strips `<style>` tags and ignores `class` attributes for custom CSS,
 * so every style that KaTeX normally applies via classes must be written as an
 * inline `style="..."` attribute.
 */
function inlineKaTeXStyles(html: string): string {
  if (typeof document === "undefined") {
    return inlineKaTeXStylesRegex(html)
  }

  const parser = new DOMParser()
  const doc = parser.parseFromString(html, "text/html")
  const rules = parseCss(katexCss as string)

  const elements = doc.body.querySelectorAll("*")
  for (const el of Array.from(elements)) {
    const inlineStyles: Record<string, string> = {}

    for (const rule of rules) {
      try {
        if (el.matches(rule.selector)) {
          Object.assign(inlineStyles, rule.styles)
        }
      } catch {
        // Ignore selectors that the browser cannot parse (e.g. pseudo-elements).
      }
    }

    if (Object.keys(inlineStyles).length > 0) {
      const existing = el.getAttribute("style") || ""
      const merged = existing
        ? `${existing};${Object.entries(inlineStyles)
            .map(([k, v]) => `${k}:${v}`)
            .join(";")}`
        : Object.entries(inlineStyles)
            .map(([k, v]) => `${k}:${v}`)
            .join(";")
      el.setAttribute("style", merged)
    }
  }

  return doc.body.innerHTML
}

function inlineKaTeXStylesRegex(html: string): string {
  const rules = parseCss(katexCss as string)

  // Process outermost wrapper elements one by one. Each formula is wrapped in
  // either <span class="katex"> (inline) or <div class="katex-display"> (block).
  return html.replace(
    /<(span|div)\s+class="katex(?:-display)?"[^>]*>[\s\S]*?<\/\1>/g,
    (formulaHtml) => {
      const parser = new DOMParser()
      const doc = parser.parseFromString(formulaHtml, "text/html")
      const root = doc.body.firstElementChild
      if (!root) return formulaHtml

      const elements = root.querySelectorAll("*")
      for (const el of Array.from(elements)) {
        const inlineStyles: Record<string, string> = {}
        for (const rule of rules) {
          // jsdom does not support element.matches, so match simple class-based
          // selectors manually.
          if (matchesSimpleSelector(el, rule.selector)) {
            Object.assign(inlineStyles, rule.styles)
          }
        }
        if (Object.keys(inlineStyles).length > 0) {
          const existing = el.getAttribute("style") || ""
          const merged = existing
            ? `${existing};${Object.entries(inlineStyles)
                .map(([k, v]) => `${k}:${v}`)
                .join(";")}`
            : Object.entries(inlineStyles)
                .map(([k, v]) => `${k}:${v}`)
                .join(";")
          el.setAttribute("style", merged)
        }
      }

      return root.outerHTML
    }
  )
}

function matchesSimpleSelector(el: Element, selector: string): boolean {
  const s = selector.trim()
  // Handle simple class selectors like .katex, .katex .base, .katex .strut
  const parts = s.split(/\s+/).filter(Boolean)
  if (parts.length === 0) return false

  let current: Element | null = el
  for (let i = parts.length - 1; i >= 0; i--) {
    if (!current) return false
    const part = parts[i]
    if (!matchesSinglePart(current, part)) return false
    current = current.parentElement
  }
  return true
}

function matchesSinglePart(el: Element, part: string): boolean {
  const classMatches = part.match(/\.([a-zA-Z0-9_-]+)/g) || []
  const tagMatch = part.match(/^[a-zA-Z0-9]+/)
  const idMatch = part.match(/#([a-zA-Z0-9_-]+)/)

  if (tagMatch && el.tagName.toLowerCase() !== tagMatch[0].toLowerCase()) {
    return false
  }
  if (idMatch && el.id !== idMatch[1]) return false
  for (const cm of classMatches) {
    const className = cm.slice(1)
    if (!el.classList.contains(className)) return false
  }
  return true
}

/**
 * Remove the MathML accessibility node that KaTeX embeds. It duplicates the
 * formula text and is normally hidden by katex.css; without that stylesheet it
 * would be visible and break the layout.
 */
function removeMathMlNode(html: string): string {
  if (typeof document === "undefined") {
    return html.replace(/<span class="katex-mathml"[\s\S]*?<\/span>/g, "")
  }

  const parser = new DOMParser()
  const doc = parser.parseFromString(html, "text/html")
  doc.body.querySelectorAll(".katex-mathml").forEach((el) => el.remove())
  return doc.body.innerHTML
}

/**
 * Replace placeholders inside rendered HTML with KaTeX output whose styles
 * have been inlined for WeChat compatibility.
 */
export function injectRenderedMath(
  html: string,
  snippets: MathSnippet[]
): string {
  let result = html

  for (const { id, tex, displayMode } of snippets) {
    try {
      let rendered = katex.renderToString(tex, {
        throwOnError: false,
        displayMode,
        strict: false,
        output: "html",
        trust: false,
      })

      rendered = removeMathMlNode(rendered)
      rendered = inlineKaTeXStyles(rendered)

      const placeholder = displayMode
        ? BLOCK_PLACEHOLDER(id)
        : INLINE_PLACEHOLDER(id)
      result = result.replace(placeholder, rendered)
    } catch {
      const fallback = displayMode
        ? `<pre style="background:#f5f5f5;padding:12px;border-radius:6px;overflow-x:auto;">${tex}</pre>`
        : `<code style="background:#f5f5f5;padding:2px 5px;border-radius:3px;">${tex}</code>`
      const placeholder = displayMode
        ? BLOCK_PLACEHOLDER(id)
        : INLINE_PLACEHOLDER(id)
      result = result.replace(placeholder, fallback)
    }
  }

  return result
}
